//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularEspacioTotal", ReplyAction="*")]
        double CalcularEspacioTotal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularEspacioTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalcularEspacioTotalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularEspacioDisponible", ReplyAction="*")]
        double CalcularEspacioDisponible();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularEspacioDisponible", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalcularEspacioDisponibleAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Winform.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Winform.ServiceReference1.WebService1Soap>, Winform.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalcularEspacioTotal() {
            return base.Channel.CalcularEspacioTotal();
        }
        
        public System.Threading.Tasks.Task<double> CalcularEspacioTotalAsync() {
            return base.Channel.CalcularEspacioTotalAsync();
        }
        
        public double CalcularEspacioDisponible() {
            return base.Channel.CalcularEspacioDisponible();
        }
        
        public System.Threading.Tasks.Task<double> CalcularEspacioDisponibleAsync() {
            return base.Channel.CalcularEspacioDisponibleAsync();
        }
    }
}
